baseURL = 'https://servopunk.net/'
locale = 'en-us'
title = 'SERVOPUNK'
theme = 'kyber'
enableRobotsTXT = true

[params]
tagline = "Build cool shit. Put it on the net."
youtube = "https://www.youtube.com/@SERVOPUNK"
mail = "info@servopunk.net"

[markup.highlight]
style = "modus-vivendi"
noClasses = false

[imaging]
quality = 80
resampleFilter = "Lanczos"

[params.imaging]
inlineRes = 1600
inlineQuality = 80
thumbnailRes = 1000
thumbnailQuality = 80
headerRes = 1600
headerQuality = 85
heroRes = 1920
heroQuality = 90

