baseURL = 'https://servopunk.net/'
locale = 'en-us'
title = 'SERVOPUNK'
theme = 'kyber'
enableRobotsTXT = true

[params]
tagline = "Build cool shit. Put it on the net."
youtube = "https://www.youtube.com/@SERVOPUNK"
mail = "info@servopunk.net"

[markup.highlight]
style = "modus-vivendi"
noClasses = false

[imaging]
quality = 80
resampleFilter = "Lanczos"

[params.imaging]
inlineRes = 1200
inlineQuality = 75
thumbnailRes = 800
thumbnailQuality = 75
headerRes = 1200
headerQuality = 80
heroRes = 1600
heroQuality = 80

